modLoader="javafml"
loaderVersion="[4,)"
license="Public Domain"

[[mods]]
modId="c418musicrestored"
version="1.0.1"
displayName="C418 Music Restored"
displayURL="https://piber.me/"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Piber"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.c418musicrestored]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.c418musicrestored]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration